image: java:8

before_script:
  - apt-get update -y
  - apt-get install apt-transport-https -y
  ## Install SBT
  - echo "deb https://dl.bintray.com/sbt/debian /" > /etc/apt/sources.list.d/sbt.list
  - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - apt-get update -y
  - apt-get install sbt -y
  - sbt sbtVersion

cache:
  paths:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

variables:
  SBT_OPTS: "-Xms1g -Xmx1g -XX:MaxMetaspaceSize=1g"

stages:
  - test

test:
  stage: test
  script: sbt clean test

